name: rustdoc
on:
  pull_request:
    branches: [ "master" ]


env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -W unreachable-pub"
  RUSTUP_MAX_RETRIES: 10

jobs:
  rustdoc:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      run: rustup update --no-self-update stable

    - name: Build Documentation
      run: cargo doc --all --no-deps

    - name: relink Github pages
      # Add redirect to uvls doc site as main Page
      run: echo '<meta http-equiv="refresh" content="0; url=./uvls" />' > ./target/doc/index.html

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@364c31d33bb99327c77b3a5438a83a357a6729ad # v3.4.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true